spring.application.name=learn_spring_boot

# H2 Console - Enable
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database
spring.datasource.url=jdbc:h2:mem:raj
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# This is important for Spring Boot 4.x
spring.web.resources.add-mappings=false